DEFAULT_LOG_DIR = '/nomad/log'
MASTER_LOG_FILE_NAME = 'nomad_master.log'
MASTER_K8S_SERVICE_ENVVAR = 'NOMADMASTER_SERVICE_SERVICE_HOST'

RPC_DEFAULT_PORT = 31000
RPC_INIT_WAIT_INTERVAL = 5

GET_NEXT_OP_RETRIES = 10
DEFAULT_DOCKER_HUB_REPO = 'lab11nomad'
