DEFAULT_LOG_DIR = '/nomad/log'
CLIENT_LOG_FILE_NAME = 'nomad_client.log'

DEFAULT_OPERATOR_DILL_PATH = '/nomad/operator.dill'

RPC_INIT_WAIT_INTERVAL = 5

MAX_INCOMING_QUEUE_SIZE = 100
MAX_OUTGOING_QUEUE_SIZE = 100